### ISSUE TITLE
SMRT dies if wget rc != 0

### ISSUE THREAD

**Issue by tk-hendrik** [csirtgadgets/csirtg-smrt-py#109]
Just detect this. My company proxy sometimes kill the conn while consuming large files. Of course a problem on my site, but should smrt really die for this while running as service?

Executed like this:
`csirtg-smrt --fireball --remember --service --client cif --service --delay 0 -d -r /etc/cif/rules/default/`

Debug output from csirtg-smrt:

```
2017-01-04 15:22:36,394 - DEBUG - csirtg_smrt.fetcher[100] - ['wget', '--header', 'User-Agent: csirtg-smrt/0.0.0a16+1.g7a01940 (csirtgadgets.org)', '--timeout=120', 'http://data.phishtank.com/data/online-valid.json.gz', '-N', '-P', '/var/lib/cif/smrt/phishtank.com']
--2017-01-04 15:22:36--  http://data.phishtank.com/data/online-valid.json.gz
Auflösen des Hostnamen »proxy.mycompany.com (proxy.mycompany.com)«... x.x.x.x
Verbindungsaufbau zu proxy.mycompany.com (proxy.mycompany.com)|x.x.x.x|:8080... verbunden.
Proxy-Anforderung gesendet, warte auf Antwort... 503 Service Unavailable
2017-01-04 15:22:40 FEHLER 503: Service Unavailable.

2017-01-04 15:22:40,573 - ERROR - csirtg_smrt.fetcher[116] - failure pulling feed: http://data.phishtank.com/data/online-valid.json.gz to /var/lib/cif/smrt/phishtank.com
Traceback (most recent call last):
  File "/etc/cif/cif-venv/lib/python2.7/site-packages/csirtg_smrt-0.0.0a16+1.g7a01940-py2.7.egg/csirtg_smrt/smrt.py", line 325, in main
    for i in s.process(r, f, limit=args.limit, data=data, filters=filters):
  File "/etc/cif/cif-venv/lib/python2.7/site-packages/csirtg_smrt-0.0.0a16+1.g7a01940-py2.7.egg/csirtg_smrt/smrt.py", line 185, in process
    for indicator_batch in feed_indicators_batches:
  File "/etc/cif/cif-venv/lib/python2.7/site-packages/csirtg_smrt-0.0.0a16+1.g7a01940-py2.7.egg/csirtg_smrt/utils/__init__.py", line 92, in chunk
    for x in it:
  File "/etc/cif/cif-venv/lib/python2.7/site-packages/csirtg_smrt-0.0.0a16+1.g7a01940-py2.7.egg/csirtg_smrt/smrt.py", line 181, in <genexpr>
    feed_indicators = (i for i in feed_indicators if not self.is_archived_with_log(i))
  File "/etc/cif/cif-venv/lib/python2.7/site-packages/csirtg_smrt-0.0.0a16+1.g7a01940-py2.7.egg/csirtg_smrt/smrt.py", line 175, in <genexpr>
    feed_indicators = (self.clean_indicator(i) for i in feed_indicators)
  File "/etc/cif/cif-venv/lib/python2.7/site-packages/csirtg_smrt-0.0.0a16+1.g7a01940-py2.7.egg/csirtg_smrt/parser/zjson.py", line 18, in process
    for l in self.fetcher.process():
  File "/etc/cif/cif-venv/lib/python2.7/site-packages/csirtg_smrt-0.0.0a16+1.g7a01940-py2.7.egg/csirtg_smrt/fetcher.py", line 118, in process
    raise e
CalledProcessError: Command '['wget', '--header', 'User-Agent: csirtg-smrt/0.0.0a16+1.g7a01940 (csirtgadgets.org)', '--timeout=120', 'http://data.phishtank.com/data/online-valid.json.gz', '-N', '-P', '/var/lib/cif/smrt/phishtank.com']' returned non-zero exit status 8
Traceback (most recent call last):
  File "/etc/cif/cif-venv/bin/csirtg-smrt", line 11, in <module>
    load_entry_point('csirtg-smrt==0.0.0a16+1.g7a01940', 'console_scripts', 'csirtg-smrt')()
  File "/etc/cif/cif-venv/lib/python2.7/site-packages/csirtg_smrt-0.0.0a16+1.g7a01940-py2.7.egg/csirtg_smrt/smrt.py", line 350, in main
    raise e
subprocess.CalledProcessError: Command '['wget', '--header', 'User-Agent: csirtg-smrt/0.0.0a16+1.g7a01940 (csirtgadgets.org)', '--timeout=120', 'http://data.phishtank.com/data/online-valid.json.gz', '-N', '-P', '/var/lib/cif/smrt/phishtank.com']' returned non-zero exit status 8


```

**Comment by tk-hendrik** [comment]
Additional or New Issue?

It also dies on sub-directories:
```
2017-01-04 15:59:19,875 - DEBUG - csirtg_smrt.smrt[87] - processing /etc/cif/rules/default//disabled
Traceback (most recent call last):
  File "/etc/cif/cif-venv/lib/python2.7/site-packages/csirtg_smrt-0.0.0a16+1.g7a01940-py2.7.egg/csirtg_smrt/smrt.py", line 324, in main
    for r, f in s.load_feeds(args.rule, feed=args.feed):
  File "/etc/cif/cif-venv/lib/python2.7/site-packages/csirtg_smrt-0.0.0a16+1.g7a01940-py2.7.egg/csirtg_smrt/smrt.py", line 88, in load_feeds
    r = Rule(path=os.path.join(rule, f))
  File "/etc/cif/cif-venv/lib/python2.7/site-packages/csirtg_smrt-0.0.0a16+1.g7a01940-py2.7.egg/csirtg_smrt/rule.py", line 27, in __init__
    raise RuleUnsupported('unsupported file type: {}'.format(path))
RuleUnsupported: unsupported file type: /etc/cif/rules/default/disabled
Traceback (most recent call last):
  File "/etc/cif/cif-venv/bin/csirtg-smrt", line 11, in <module>
    load_entry_point('csirtg-smrt==0.0.0a16+1.g7a01940', 'console_scripts', 'csirtg-smrt')()
  File "/etc/cif/cif-venv/lib/python2.7/site-packages/csirtg_smrt-0.0.0a16+1.g7a01940-py2.7.egg/csirtg_smrt/smrt.py", line 350, in main
    raise e
csirtg_smrt.exceptions.RuleUnsupported: unsupported file type: /etc/cif/rules/default/disabled
```

**Comment by wesyoung** [comment]
smrt dies "even as a service" on purpose, so we find this stuff... the assumption being; if we find enough of this stuff.. it won't die and when it does; it shouldn't so we'll make it better faster.. (i think?)

can you log the second as a sep bug; i'll try to knock them both out (should be easy enough).

**Comment by wesyoung** [comment]
looking at the code, in debug mode it's supposed to roll over and die; but in non debug mode it's just supposed to log the error and move on

https://github.com/csirtgadgets/csirtg-smrt-py/blob/master/csirtg_smrt/fetcher.py#L117

if you run it w/o the -d, does it fall over?
