### ISSUE TITLE
InvalidIndicator: unknown itype for "xn--1--blcfn0a0ai7a1a7e.xn--p1acf"

### ISSUE THREAD

**Issue by tk-hendrik** [csirtgadgets/csirtg-smrt-py#131]
SMRT Dies with:
```
Feb 10 14:28:46 localhost csirtg-smrt[165393]: Process Process-1:
Feb 10 14:28:46 localhost csirtg-smrt[165393]: Traceback (most recent call last):
Feb 10 14:28:46 localhost csirtg-smrt[165393]:   File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
Feb 10 14:28:46 localhost csirtg-smrt[165393]:     self.run()
Feb 10 14:28:46 localhost csirtg-smrt[165393]:   File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
Feb 10 14:28:46 localhost csirtg-smrt[165393]:     self._target(*self._args, **self._kwargs)
Feb 10 14:28:46 localhost csirtg-smrt[165393]:   File "/etc/cif/cif-venv/local/lib/python2.7/site-packages/csirtg_smrt/smrt.py", line 252, in _run_smrt
Feb 10 14:28:46 localhost csirtg-smrt[165393]:     for i in s.process(r, f, limit=args.limit, data=data, filters=filters):
Feb 10 14:28:46 localhost csirtg-smrt[165393]:   File "/etc/cif/cif-venv/local/lib/python2.7/site-packages/csirtg_smrt/smrt.py", line 212, in process
Feb 10 14:28:46 localhost csirtg-smrt[165393]:     for indicator_batch in feed_indicators_batches:
Feb 10 14:28:46 localhost csirtg-smrt[165393]:   File "/etc/cif/cif-venv/local/lib/python2.7/site-packages/csirtg_smrt/utils/__init__.py", line 92, in chunk
Feb 10 14:28:46 localhost csirtg-smrt[165393]:     for x in it:
Feb 10 14:28:46 localhost csirtg-smrt[165393]:   File "/etc/cif/cif-venv/local/lib/python2.7/site-packages/csirtg_smrt/smrt.py", line 208, in <genexpr>
Feb 10 14:28:46 localhost csirtg-smrt[165393]:     feed_indicators = (i for i in feed_indicators if not self.is_archived_with_log(i))
Feb 10 14:28:46 localhost csirtg-smrt[165393]:   File "/etc/cif/cif-venv/local/lib/python2.7/site-packages/csirtg_smrt/smrt.py", line 202, in <genexpr>
Feb 10 14:28:46 localhost csirtg-smrt[165393]:     feed_indicators = (self.clean_indicator(i, rule) for i in feed_indicators)
Feb 10 14:28:46 localhost csirtg-smrt[165393]:   File "/etc/cif/cif-venv/local/lib/python2.7/site-packages/csirtg_smrt/smrt.py", line 153, in clean_indicator
Feb 10 14:28:46 localhost csirtg-smrt[165393]:     i = normalize_itype(i)
Feb 10 14:28:46 localhost csirtg-smrt[165393]:   File "build/bdist.linux-x86_64/egg/csirtg_indicator/utils/__init__.py", line 174, in normalize_itype
Feb 10 14:28:46 localhost csirtg-smrt[165393]:     i = _normalize_url(i)
Feb 10 14:28:46 localhost csirtg-smrt[165393]:   File "build/bdist.linux-x86_64/egg/csirtg_indicator/utils/__init__.py", line 204, in _normalize_url
Feb 10 14:28:46 localhost csirtg-smrt[165393]:     if resolve_itype(i['indicator'], test_broken=True) == 'broken_url':
Feb 10 14:28:46 localhost csirtg-smrt[165393]:   File "build/bdist.linux-x86_64/egg/csirtg_indicator/utils/__init__.py", line 154, in resolve_itype
Feb 10 14:28:46 localhost csirtg-smrt[165393]:     raise InvalidIndicator(error)
Feb 10 14:28:46 localhost csirtg-smrt[165393]: InvalidIndicator: unknown itype for "xn--1--blcfn0a0ai7a1a7e.xn--p1acf"

```

**Comment by wesyoung** [comment]
logged over here:

https://github.com/csirtgadgets/csirtg-indicator-py/issues/65
