### ISSUE TITLE
problem: key error with phishtank feed

### ISSUE THREAD

**Issue by wesyoung** [csirtgadgets/csirtg-smrt-py#132]
```
csirtg-smrt -d -r /etc/cif/rules/default/phishtank.yml
<< snip >>
2017-02-08 01:02:02,802 - DEBUG - csirtg_smrt.smrt[174] - adding: httXs://www[.]2freehosting[.]com/dropboxx/dropboxx/transf.html/phishtank.com/2016-11-09 19:56:47+00:00/2016-11-09 19:56:47+00:00
2017-02-08 01:02:02,802 - DEBUG - csirtg_smrt.smrt[174] - adding: httX://refreshdharan[.]com/bg/excel2/index.php?userid={dong[.]keonkwonfinancialconsultd[@]yahoo[.]com}/phishtank.com/2016-11-09 19:56:16+00:00/2016-11-09 19:56:16+00:00
Traceback (most recent call last):
  File "/usr/local/bin/csirtg-smrt", line 9, in <module>
    load_entry_point('csirtg-smrt==0.0.0a22', 'console_scripts', 'csirtg-smrt')()
  File "/usr/local/lib/python2.7/dist-packages/csirtg_smrt/smrt.py", line 359, in main
    'goback': goback
  File "/usr/local/lib/python2.7/dist-packages/csirtg_smrt/smrt.py", line 252, in _run_smrt
    for i in s.process(r, f, limit=args.limit, data=data, filters=filters):
  File "/usr/local/lib/python2.7/dist-packages/csirtg_smrt/smrt.py", line 222, in process
    yield list(i.format_keys())[0]
  File "/usr/local/lib/python2.7/dist-packages/csirtg_indicator/indicator.py", line 119, in format_keys
    d[k] = d[k].format(**d)
KeyError: u'dong'
```

**Comment by wesyoung** [comment]
fixed via https://github.com/csirtgadgets/csirtg-indicator-py/pull/68
