### ISSUE TITLE
problem: ssl error kill smrt

### ISSUE THREAD

**Issue by wesyoung** [csirtgadgets/csirtg-smrt-py#138]
```
2017-02-15 14:05:06,365 - INFO - csirtg_smrt.archiver[115] - Cached provider nothink.org in memory, 0 objects
Process Process-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python2.7/dist-packages/csirtg_smrt/smrt.py", line 273, in _run_smrt
    for i in s.process(r, f, limit=args.limit, data=data, filters=filters):
  File "/usr/local/lib/python2.7/dist-packages/csirtg_smrt/smrt.py", line 233, in process
    for indicator_batch in feed_indicators_batches:
  File "/usr/local/lib/python2.7/dist-packages/csirtg_smrt/utils/__init__.py", line 93, in chunk
    for x in it:
  File "/usr/local/lib/python2.7/dist-packages/csirtg_smrt/smrt.py", line 229, in <genexpr>
    feed_indicators = (i for i in feed_indicators if not self.is_archived_with_log(i))
  File "/usr/local/lib/python2.7/dist-packages/csirtg_smrt/smrt.py", line 223, in <genexpr>
    feed_indicators = (self.clean_indicator(i, rule) for i in feed_indicators)
  File "/usr/local/lib/python2.7/dist-packages/csirtg_smrt/smrt.py", line 222, in <genexpr>
    feed_indicators = (i for i in feed_indicators if self.is_valid(i, rule))
  File "/usr/local/lib/python2.7/dist-packages/csirtg_smrt/parser/pattern.py", line 33, in process
    for l in self.fetcher.process(split=self.split):
  File "/usr/local/lib/python2.7/dist-packages/csirtg_smrt/fetcher.py", line 224, in process
    self._fetch()
  File "/usr/local/lib/python2.7/dist-packages/csirtg_smrt/fetcher.py", line 184, in _fetch
    self._cache_write(s)
  File "/usr/local/lib/python2.7/dist-packages/csirtg_smrt/fetcher.py", line 163, in _cache_write
    resp = s.get(self.remote, stream=True, auth=auth, timeout=self.fetcher_timeout)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 501, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 497, in send
    raise SSLError(e, request=request)
SSLError: [Errno 1] _ssl.c:510: error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure
```

**Comment by JustinAzoff** [comment]
fyi.. that's not actually a 500 error, it's a SSL error.

Can be quite a pain to deal with those
