### ISSUE TITLE
(csirtg_smrt-0.0.0a24) IndexError: list index out of range

### ISSUE THREAD

**Issue by tk-hendrik** [csirtgadgets/csirtg-smrt-py#151]
Sorry for just throwing this in without debug output - I ran out of time.
Hope this output may help to find what may be wrong...

```
Feb 21 08:05:14 localhost csirtg-smrt[115945]: 2017-02-21 08:05:14,612 - INFO - csirtg_smrt.archiver[105] - Caching archived indicators for provider csirtg.io
Feb 21 08:05:14 localhost csirtg-smrt[115945]: 2017-02-21 08:05:14,675 - INFO - csirtg_smrt.archiver[115] - Cached provider csirtg.io in memory, 0 objects
Feb 21 08:05:15 localhost csirtg-smrt[115945]: Process Process-2:
Feb 21 08:05:15 localhost csirtg-smrt[115945]: Traceback (most recent call last):
Feb 21 08:05:15 localhost csirtg-smrt[115945]:   File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
Feb 21 08:05:15 localhost csirtg-smrt[115945]:     self.run()
Feb 21 08:05:15 localhost csirtg-smrt[115945]:   File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
Feb 21 08:05:15 localhost csirtg-smrt[115945]:     self._target(*self._args, **self._kwargs)
Feb 21 08:05:15 localhost csirtg-smrt[115945]:   File "/etc/cif/cif-venv/lib/python2.7/site-packages/csirtg_smrt-0.0.0a24-py2.7.egg/csirtg_smrt/smrt.py", line 273, in _run_smrt
Feb 21 08:05:15 localhost csirtg-smrt[115945]:     for i in s.process(r, f, limit=args.limit, data=data, filters=filters):
Feb 21 08:05:15 localhost csirtg-smrt[115945]:   File "/etc/cif/cif-venv/lib/python2.7/site-packages/csirtg_smrt-0.0.0a24-py2.7.egg/csirtg_smrt/smrt.py", line 233, in process
Feb 21 08:05:15 localhost csirtg-smrt[115945]:     for indicator_batch in feed_indicators_batches:
Feb 21 08:05:15 localhost csirtg-smrt[115945]:   File "/etc/cif/cif-venv/lib/python2.7/site-packages/csirtg_smrt-0.0.0a24-py2.7.egg/csirtg_smrt/utils/__init__.py", line 93, in chunk
Feb 21 08:05:15 localhost csirtg-smrt[115945]:     for x in it:
Feb 21 08:05:15 localhost csirtg-smrt[115945]:   File "/etc/cif/cif-venv/lib/python2.7/site-packages/csirtg_smrt-0.0.0a24-py2.7.egg/csirtg_smrt/smrt.py", line 229, in <genexpr>
Feb 21 08:05:15 localhost csirtg-smrt[115945]:     feed_indicators = (i for i in feed_indicators if not self.is_archived_with_log(i))
Feb 21 08:05:15 localhost csirtg-smrt[115945]:   File "/etc/cif/cif-venv/lib/python2.7/site-packages/csirtg_smrt-0.0.0a24-py2.7.egg/csirtg_smrt/smrt.py", line 223, in <genexpr>
Feb 21 08:05:15 localhost csirtg-smrt[115945]:     feed_indicators = (self.clean_indicator(i, rule) for i in feed_indicators)
Feb 21 08:05:15 localhost csirtg-smrt[115945]:   File "/etc/cif/cif-venv/lib/python2.7/site-packages/csirtg_smrt-0.0.0a24-py2.7.egg/csirtg_smrt/smrt.py", line 222, in <genexpr>
Feb 21 08:05:15 localhost csirtg-smrt[115945]:     feed_indicators = (i for i in feed_indicators if self.is_valid(i, rule))
Feb 21 08:05:15 localhost csirtg-smrt[115945]:   File "/etc/cif/cif-venv/lib/python2.7/site-packages/csirtg_smrt-0.0.0a24-py2.7.egg/csirtg_smrt/parser/delim.py", line 34, in process
Feb 21 08:05:15 localhost csirtg-smrt[115945]:     i[col] = m[idx]
Feb 21 08:05:15 localhost csirtg-smrt[115945]: IndexError: list index out of range
```

**Comment by wesyoung** [comment]
no worries; i think one of the columns may be off in the config. i just released smrt-a26 and cifa16 which i think? fixes this (i say i think cause i vaguely remember something like this ..).

quick work-around maybe:

```
$ pip install csirtg-smrt==0.0.0a26
```

and pull the latest csirtgio.yml file to see if that helps:

https://github.com/csirtgadgets/bearded-avenger/commit/526338f466b55849e13cdccefcbc302c8626b512#diff-4842cff9d09172a5b9d8b81d748f7427

(actually, maybe try the new yaml file first, then try upgrading smrt...?)

make sense?
